=== a-hagar/ticket-support-system/xml/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user"  minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="userid" />
                            <xs:element name="username" />
                            <xs:element name="password" />
                            <xs:element name="name">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="firstname" maxOccurs="unbounded"/>
                                        <xs:element name="lastname" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                        <xs:attribute name="userType" type="xs:string" use="required"/>
                        <xs:attribute name="isAdmin" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== a-hagar/ticket-support-system/xml/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="users.xsd">
    <user userType="client" isAdmin="no">
        <userid>1</userid>
        <username>johndoe</username>
        <password>test1</password>
        <name>
            <firstname>John</firstname>
            <lastname>Doe</lastname>
        </name>
    </user>
    <user userType="support" isAdmin="yes">
        <userid>2</userid>
        <username>adminJames</username>
        <password>admin</password>
        <name>
            <firstname>James</firstname>
            <lastname>Smith</lastname>
        </name>
    </user>
    <user userType="client" isAdmin="no">
        <userid>3</userid>
        <username>ahagar1</username>
        <password>test3</password>
        <name>
            <firstname>Ahmed</firstname>
            <lastname>Hagar</lastname>
        </name>
    </user>
    <user userType="client" isAdmin="no">
        <userid>4</userid>
        <username>redd0livia</username>
        <password>test4</password>
        <name>
            <firstname>Olivia</firstname>
            <lastname>Redd</lastname>
        </name>
    </user>
</users>
